# Generated by Django 4.2.4 on 2023-08-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='members',
            new_name='sender',
        ),
    ]
