# Generated by Django 4.2.4 on 2023-08-08 11:00

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.upload_icon_category),
        ),
    ]
