# Generated by Django 4.2.4 on 2023-08-11 11:04

from django.db import migrations, models
import django.db.models.deletion
import server.models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_category_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_upload_banner_category, validators=[server.validators.validate_icon_file_extension]),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_upload_icon_category, validators=[server.validators.validate_icon_image_size, server.validators.validate_icon_file_extension]),
        ),
        migrations.AlterField(
            model_name='server',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_category', to='server.category'),
        ),
    ]
